### ISSUE TITLE
Template Test Findings

### ISSUE THREAD

**Issue by jbaikge** [go-goods/tmpl#11]
(Below references 0300c67c42b592b0162789e47298ff8c5474005e)

Used FIXME as a popout nomenclature, not expecting anything to be a broken thing just yet.
1. _Lines 18-21_ Is this expected behavior? I don't mind that {#} compiles to an empty comment, could be a neat feature for de-commenting large blocks
2. _Lines 26 & 29_ Looks like whitespace is required between the trailing character of a selector and the closing delimiter
3. _Line 35_ Should []byte get cast to a string?
4. _Lines 38-44_ Not sure how else I'd spit out a list other than the native representation. They're meant to be range'd over anyways
5. _Lines 53-55_ Panic at le disco. Really tried to hunt down what was happening via the stack trace, all I can make out is somewhere a nil pointer is getting dereferenced. Tried substituting the nil context with d{} and d{"foo":"bar"} with no luck

**Comment by zeebo** [comment]
abf181ea1a63f9e9f45f6f15e83965c34de68ae6
![fix all the things](http://i.imgur.com/Txx0q.jpg)
