### ISSUE TITLE
Empty Definitions

### ISSUE THREAD

**Issue by jbaikge** [go-goods/tmpl#16]
Are empty definitions (below) valid? Currently, they lex and compile.

```
{%%}
{% %}
```

**Comment by zeebo** [comment]
I'm ok with that. I wouldn't mind making it an error though as I think it's a simple change to the parser.

**Comment by jbaikge** [comment]
I agree with making it an error for the sake of ship-shape templates.

**Comment by zeebo** [comment]
accepted.
