### ISSUE TITLE
Add a bunch of simple unit tests for parsing/lexing

### ISSUE THREAD

**Issue by zeebo** [go-goods/tmpl#2]
All the unit tests are really terrible and test far too much. We need much simpler unit tests to check things are actually working in simple cases like {% block foo %}{% end block %} parses and {% . %} lexes into [open, startSel, push, endSel, close] etc. etc.

**Comment by jbaikge** [comment]
d168b3255b59a886a9c1fb3033366ac5c1ace658 - Added a few super simple tests to try to trick the compiler
