### ISSUE TITLE
Range default values

### ISSUE THREAD

**Issue by zeebo** [go-goods/tmpl#20]
If you do not specify the names for the variables for range to use, it doesn't use any and basically does nothing.

**Comment by zeebo** [comment]
I'm gonna tackle this one.

**Comment by jbaikge** [comment]
1b1ac0608f5acd74ee86fdf4ac946ed204f58429 - Test is in with the following output, currently:

```
--- FAIL: TestTemplatePassRanges (0.00 seconds)
    template_test.go:215: 8: /.key: Error accessing item 0: "key"
```

**Comment by zeebo** [comment]
Technically not closed yet because the code review in the pull request has not passed.

# ROBOT HOUSEEEEEEEEE
