### ISSUE TITLE
Check for \r in the lexer?

### ISSUE THREAD

**Issue by jbaikge** [go-goods/tmpl#7]
In the switch inside of lexInsideDelims, should we add `|| r == '\r'` to the first case?

**Comment by zeebo** [comment]
I was against allowing newlines inside of {% %} tags. It might be nice if we allow things like inline dictionaries or lists thought.

**Comment by zeebo** [comment]
ugh I dont know why I thought adding a '\r' would make it be allowed to add newlines inside of actions. I'd say it's a good idea to check for '\r' then.

**Comment by zeebo** [comment]
fixed by dda7487
