### ISSUE TITLE
Pushing on previous contexts

### ISSUE THREAD

**Issue by zeebo** [go-goods/tmpl#8]
Assume we have this template

```
{% block foo $$.foo %}{% $.bar %}{% end block %}
```

how does this exactly work? say we're at the level /1/2/foo/3/4, so that the $$.foo would be selecting /1/2/foo, what does $.bar select? is it /1/2/foo/3/4/bar or /1/2/bar?

The first case is motivated by the idea that block always pushes a value on to the current stack. We selected the value /1/2/foo and so that gets appended to the current stack making the context /1/2/foo/3/4/foo, at which point we pop and select bar, so /1/2/foo/3/4/bar.

The second case is motivated by the idea of selecting our context for the block, so instead of the idea of pushing on to the stack, we're selecting where in the stack we will be inside of the block context.

I feel like if we do the second case, we should add support for the most top level element, maybe with some special selector identifier like uhhhhhh & or something we haven't used, but thats getting complicated. Thoughts?

**Comment by zeebo** [comment]
Forgot to mention, {% with %} has this same problem.

**Comment by jbaikge** [comment]
I kind of see blocks as their own entity, similar to a function call.

If we have a block that we plan on reusing, where we pass in the context and rely on second case's behavior, we can safely determine the path every time.

For example:

```
{% block name %}{% .firstName %} {% .lastName %} - {% $.bar %}{% end block %}

... HTML header and such ...

Hello, {% block name loggedInUser %}

... More HTML ...

{% range friends as _ u %}
    {% if u.active %}
        Your friend is {% name u %}<br>
    {% end if %}
{% end range %}
```

If the context of the first call is /loggedInUser, then $.bar clearly references /bar

But in the second call, where we use u, I'm not sure what that context is, and whether $.bar will find the correct one.

**Comment by zeebo** [comment]
Ranges will be using variables. So that will look like

```
{% range .friends as _ u %}
    {% if ^u.active %}
        Your friend is {% block name ^u %}<br>
    {% end if %}
{% end range %}
```

I decided to make ranges not modify the context because it's difficult to think of a way for them to do it right.

That does illustrate a point in that ^u has no path anywhere in the context, and so we sorta need to push directly on to the current context.

I'm really beginning to wonder if I want to keep popping past obvious context boundaries like blocks. I can't think of a case where it would mess up with {% with %} with the idea that a {% with %} just changes the context path.

**Comment by zeebo** [comment]
What do you think about making pop really only work inside of {% with %} statements, so the only real value they get is when you have to do something like,

```
{% .user.firstName %}
{% .user.lastName %}
{% if .isAdmin %} admin {% end if %}
{% .user.something %}
```

->

```
{% with .user %}
    {% .firstName %}
    {% .lastName %}
    {% if $.isAdmin %} admin {% end if %}
    {% .something %}
{% end with %}
```

Then the pop has obvious semantics. With changes what the current context is, and pop goes out past it. So if we move all those attributes to an info attribute on the user, all that has to change is

```
{% with .user.info %}
    {% .firstName %}
    {% .lastName %}
    {% if $$.isAdmin %} admin {% end if %}
    {% .something %}
{% end with %}
```

Blocks root the context at the passed in value so you can't go out past it.

**Comment by zeebo** [comment]
I feel like if we go with the context boundary idea we need to be able to pass in dictionaries.

**Comment by jbaikge** [comment]
I really like the simplicity there, and it keeps things easy to understand.

As far as passing in dictionaries for fenced context, I think that's a
very valid point and will make the templates a lot more explicit and
legible.

**Comment by zeebo** [comment]
What about doing something like

```
{% set foo .user.info %}
{% with ^foo %}
    {% .firstName %}
    {% .lastName %}
    {% if $.isAdmin %} admin {% end if %}
    {% .something %}
{% end with %}
```

we're still back at the push/pop problem.

**Comment by jbaikge** [comment]
I guess it goes back to #6 and whether you'd store set's as values or references.

If it was something like

```
{% set foo {"firstName": "foo", "lastName": "bar", "something": "baz"} %}
{% with ^foo %}
    ...
{% end with %}
```

You'd have to store the value and then $ would be completely useless.

**Comment by zeebo** [comment]
The real issue is conflating the ideas of a path to a value and an actual value. I want to separate those ideas without imposing too heavy a syntax.

**Comment by zeebo** [comment]
Having thought over it, the issue really is that variables aren't part of the path. Perhaps we have variables rooted at /vars.<varname>, where "/" represents the top level context, or where ever you set them, and they overwrite what was at that path. For example,

```
{% set var "foo" %}
{% /vars.foo %}
```

or

```
{% set .vars.foo "foo" %}
{% .vars.foo %}
{% set .user.isAdmin 1 %}
{% .user.isAdmin %}
```

in the second case, set now isnt setting a variable, it's setting a path in the context.

**Comment by zeebo** [comment]
The first proposal idea is exactly the same as the variable idea removed before in #6 , just replace /vars with ^ to see why.

ranges, blocks, and with statements require a selector path as the context to ensure we're always able to pop and absolute path correctly. All of the following lines will print the same thing assuming that we start at the root context

```
{% with .foo.bar.baz %}
    {% .bif %}
    {% $.baz.bif %}
    {% $$.bar.baz.bif %}
    {% $$$.foo.bar.baz.bif %}
    {% /.foo.bar.baz.bif %}
{% end with %}
```

range follows in a similar fashion. range will add two values to the current selector path as specified by the user (see #5).

blocks are now considered definitions, and evoke is where the context will be specified. They work in exactly the same way as with/range.

Relative selectors just change the current selector path, so

```
{% with .foo.bar %}
    {% .baz.bif %}
    {% with .baz %}
        {% .bif %}
    {% end with %}
    {% with $.bar %}
        {% .baz.bif %}
    {% end with %}
    {% with .OOPS %}
        {% $.baz.bif %}
    {% end with %}
    {% with .baz.bif %}
        {% . %}
        {% /.foo.bar.baz.bif %}
    {% end with %}
{% end with %}
```

all print the same value assuming all selector paths exist.
